### ISSUE TITLE
add package for Scala2.10

### ISSUE THREAD

**Issue by nobusue** [kimutansk/kafka-installer#1]
Spark1.0がScala2.10を要求するので、KafkaもScala2.10版のバイナリがあると嬉しいです。
Forkさせていただいたのですが、よく考えてみたらKafkaのバイナリを入れ替えるだけだったので、試しに作成してみました。よろしければこちらにマージしていただけますか?

https://github.com/nobusue/kafka-installer/wiki/Download2

**Comment by kimutansk** [comment]
利用いただきありがとうございます。
Sparkは0.9系から確かにScala2.10系になっていますね。

作成の方もありがとうございます。
Kafkaのバイナリをそのまま展開して使用しているので、入れ替えれば確かに2.10系に出来ますね。
中身を確認後、マージさせていただきます。

**Comment by kimutansk** [comment]
内容確認完了しました。

マージさせていただきたいのですが、
作成いただいたファイルをKafka-Installerで元々使用していたS3上にアップさせていただき、
Kafka-Installerのページに載せるという形でよろしいでしょうか？

**Comment by nobusue** [comment]
ご確認ありがとうございます。

> 作成いただいたファイルをKafka-Installerで元々使用していたS3上にアップさせていただき、
> Kafka-Installerのページに載せるという形でよろしいでしょうか？

はい、その方法でお願いします。(完了後、こちらのファイルは削除予定です。)

**Comment by kimutansk** [comment]
回答ありがとうございます。

作成いただいたファイルをKafka-Installerで元々使用していたS3上にアップし、
Downloadのページに2.10のバージョンを追加しました。

https://github.com/kimutansk/kafka-installer/wiki/Download

Kafka-0.8.2系ではScala-2.10.1系がデフォルトになっているようですが、
今後も新バージョンがリリースされたらScalaも複数バージョン用意させていただきますね。
